# -*- coding: utf-8 -*-
"""GRUPO_15_Tarea2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TM5mXihxKOZYnMYKbSSRVdzQfeTyoYu0

Pregunta 1
"""

# !pip install pandas

import pandas as pd

data_ciudades={'Ciudad':['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Iquitos', 'Huancayo', 'Tacna', 'Pucallpa'],'Habitantes': [10479996, 1001690, 923331, 428450, 305717, 484475, 441649, 385098, 294395, 283734],
               'Area_km2': [2672.28, 1545.77, 1487.7, 116.5, 279.89, 6217.26, 368.9, 109.19, 59.4, 483.44],
               'Altitud_m': [154, 2325, 34, 3399, 29, 29, 106, 3271, 562, 156],
 'Densidad_poblacion_por_km2': [3924, 64.8, 62.1, 3673, 1091.6, 77.9, 1196, 3528.6, 4966, 587.2]}

nfo = pd.DataFrame( data_ciudades)
print(nfo)

columnas = ['Ciudad', 'Habitantes', 'Area_km2', 'Altitud_m', 'Densidad_poblacion_por_km2']
fila_1 = ['Lima', 10479996, 2672.28, 154, 3924]
fila_2 = ['Arequipa', 1001690, 1545.77, 2325, 64.8]
fila_3 = ['Trujillo', 923331, 1487.7, 34, 62.1]
fila_4 = ['Cusco', 428450, 116.5, 3399, 3673]
fila_5 = ['Chiclayo', 305717, 279.89, 29, 1091.6]
fila_6 = ['Piura', 484475, 6217.26, 29, 77.9]
fila_7 = ['Iquitos', 441649, 368.9, 106, 1196]
fila_8 = ['Huancayo', 385098, 109.19, 3271, 3528.6]
fila_9 = ['Tacna', 294395, 59.4, 562, 4966]
fila_10 = ['Pucallpa', 283734, 483.44, 156, 587.2]

data_1 = [fila_1, fila_2, fila_3, fila_4, fila_5, fila_6, fila_7, fila_8, fila_9, fila_10]

nfo = pd.DataFrame(data=data_1, columns=columnas)

nfo

"""Pregunta 2"""

data_ciudades_2={ 'Ciudad': ['Lima', 'Arequipa', 'Trujillo', 'Cusco','Chiclayo', 'Piura', 'Iquitos', 'Huancayo', 'Tacna', 'Pucallpa'],'Gentilicio': ['Limeño', 'Arequipeño', 'Trujillano', 'Cusqueño', 'Chiclayano', 'Piurano', 'Iquiteño', 'Huancaíno', 'Tacneño', 'Pucallpino'],
                 'Provincia': ['Lima','Arequipa', 'Trujillo','Cusco', 'Chiclayo', 'Piura', 'Maynas', 'Huancayo', 'Tacna', 'Coronel Portillo'],
                  'Region':['Lima', 'Arequipa', 'La Libertad', 'Cusco', 'Lambayeque', 'Piura', 'Loreto', 'Junín', 'Tacna', 'Ucayali']}

nombres=pd.DataFrame(data_ciudades_2)
nombres

"""Pregunta 3

"""

df_merged_1 = pd.merge(nfo, nombres, on='Ciudad', how='inner')
df_merged_1

"""Pregunta 4"""

df_merged_1.describe()

"""La mínima densidad poblacional es 62.100000 y corresponde a la ciudad de Trujillo y la máxima densidad poblacional es 4966.000000 y corresponde a la ciudad de Tacna.

Pregunta 5
"""

import numpy as np
from scipy.stats import binom
import matplotlib.pyplot as plt

df = pd.DataFrame(data_ciudades)
df.set_index('Ciudad', inplace=True)

fig, ax = plt.subplots(figsize=(12, 6))
ax.bar(df.index, df['Habitantes'], color='blue')

ax.set_xlabel('Ciudad')
ax.set_ylabel('Habitantes')
ax.set_title('Habitantes por Ciudad en Perú')

ax.tick_params(axis='x', rotation=90)

plt.show()